-- =====================================================================
-- Migration: Create Core Domain Tables
-- =====================================================================
-- Purpose: Create main application tables for flashcards and review tracking
-- Affected Tables: ai_batches, flashcards, review_sessions, review_history,
--                  flashcard_favourites
-- Special Considerations:
--   - ai_batches created first as it's referenced by flashcards
--   - UUID v7 used for all primary keys (better index locality)
--   - Foreign key constraints enforce referential integrity
--   - Cascading deletes configured where appropriate
-- =====================================================================

-- =====================================================================
-- TABLE: ai_batches (Phase 2 placeholder)
-- =====================================================================
-- Purpose: Track batches of AI-generated flashcards
-- This is a placeholder table for Phase 2 functionality
-- Will store metadata about AI generation requests and their status

create table public.ai_batches (
  -- Primary key: UUID v7 for time-ordered IDs
  id uuid primary key default public.uuid_generate_v7(),
  
  -- Owner reference: which user requested this AI batch
  user_id uuid not null references auth.users(id) on delete cascade,
  
  -- AI model identifier (e.g., "gpt-4", "claude-3-opus")
  model varchar(120) not null,
  
  -- Batch processing status (e.g., "pending", "processing", "completed", "failed")
  status varchar(40) not null default 'pending',
  
  -- Timestamp when the AI generation was requested
  requested_at timestamp with time zone not null default now()
);

comment on table public.ai_batches is 'Tracks batches of AI-generated flashcards (Phase 2 feature)';
comment on column public.ai_batches.id is 'UUID v7 primary key';
comment on column public.ai_batches.user_id is 'User who requested the AI generation';
comment on column public.ai_batches.model is 'AI model used for generation';
comment on column public.ai_batches.status is 'Current status of the batch processing';

-- =====================================================================
-- TABLE: flashcards
-- =====================================================================
-- Purpose: Core entity storing individual flashcards with spaced repetition metadata
-- Each card belongs to a user and tracks its review schedule via SuperMemo SM-2 algorithm

create table public.flashcards (
  -- Primary key: UUID v7 for time-ordered IDs
  id uuid primary key default public.uuid_generate_v7(),
  
  -- Owner reference: which user owns this flashcard
  user_id uuid not null references auth.users(id) on delete cascade,
  
  -- Card content: front side (question/prompt)
  -- Max 120 characters to encourage concise questions
  front varchar(120) not null,
  
  -- Card content: back side (answer)
  -- Max 300 characters for reasonably detailed answers
  back varchar(300) not null,
  
  -- Optional subject categorization (e.g., "mathematics", "history")
  -- Nullable to allow uncategorized cards
  subject varchar(40),
  
  -- Spaced repetition scheduling: when should this card be reviewed next
  -- Defaults to today (new cards are immediately available for review)
  next_review_at date not null default current_date,
  
  -- Spaced repetition tracking: when was this card last reviewed
  -- Null for cards that have never been reviewed
  last_review_at timestamp with time zone,
  
  -- Spaced repetition tracking: total number of times reviewed
  -- Used for statistics and algorithm adjustments
  review_count integer not null default 0,
  
  -- Spaced repetition algorithm: SM-2 ease factor
  -- Default 2.50 is the standard SM-2 starting value
  -- Range typically 1.30 to 2.50+ (lower = more frequent reviews)
  ease_factor numeric(4,2) not null default 2.50,
  
  -- Card origin: how was this card created
  -- 'manual' = created by user, 'ai' = generated by AI
  source text not null default 'manual' check (source in ('manual', 'ai')),
  
  -- Optional reference to AI batch if this card was AI-generated
  -- Null for manually created cards
  ai_batch_id uuid references public.ai_batches(id) on delete set null,
  
  -- Audit fields: when was this card created
  created_at timestamp with time zone not null default now(),
  
  -- Audit fields: when was this card last modified
  -- Updated automatically by trigger (to be created in later migration)
  updated_at timestamp with time zone not null default now(),
  
  -- Optimistic locking: version counter to prevent concurrent update conflicts
  -- Incremented automatically by trigger (to be created in later migration)
  version integer not null default 1
);

comment on table public.flashcards is 'Core flashcard entities with spaced repetition metadata';
comment on column public.flashcards.front is 'Question or prompt (max 120 chars)';
comment on column public.flashcards.back is 'Answer or explanation (max 300 chars)';
comment on column public.flashcards.subject is 'Optional category for organization';
comment on column public.flashcards.next_review_at is 'Date when card should next be reviewed (SM-2 algorithm)';
comment on column public.flashcards.ease_factor is 'SM-2 ease factor (lower = more frequent reviews)';
comment on column public.flashcards.source is 'Origin: manual (user-created) or ai (generated)';
comment on column public.flashcards.version is 'Optimistic lock version counter';

-- =====================================================================
-- TABLE: review_sessions
-- =====================================================================
-- Purpose: Track discrete review sessions (when user sits down to review cards)
-- Allows grouping of review history entries and session analytics

create table public.review_sessions (
  -- Primary key: UUID v7 for time-ordered IDs
  id uuid primary key default public.uuid_generate_v7(),
  
  -- Owner reference: which user is conducting this review session
  user_id uuid not null references auth.users(id) on delete cascade,
  
  -- Session start timestamp
  started_at timestamp with time zone not null default now(),
  
  -- Session end timestamp (null while session is active)
  finished_at timestamp with time zone,
  
  -- Session status: active, completed, or aborted
  status public.review_session_status_enum not null default 'active'
);

comment on table public.review_sessions is 'Discrete review sessions for grouping and analytics';
comment on column public.review_sessions.status is 'Session lifecycle: active, completed, or aborted';
comment on column public.review_sessions.finished_at is 'When session ended (null if still active)';

-- =====================================================================
-- TABLE: review_history
-- =====================================================================
-- Purpose: Immutable log of every flashcard review attempt
-- Stores user's difficulty rating and response time for analytics
-- Drives the spaced repetition algorithm

create table public.review_history (
  -- Primary key: UUID v7 for time-ordered IDs
  id uuid primary key default public.uuid_generate_v7(),
  
  -- Foreign key: which flashcard was reviewed
  -- CASCADE: when flashcard is deleted, remove its review history
  flashcard_id uuid not null references public.flashcards(id) on delete cascade,
  
  -- Foreign key: which user performed the review
  user_id uuid not null references auth.users(id) on delete cascade,
  
  -- Foreign key: which review session this review belongs to (optional)
  -- Null for reviews performed outside formal sessions
  session_id uuid references public.review_sessions(id) on delete set null,
  
  -- User's self-reported difficulty: hard, medium, or easy
  -- This drives the SM-2 algorithm adjustments
  difficulty public.difficulty_enum not null,
  
  -- Server timestamp: when the review was recorded
  answered_at timestamp with time zone not null default now(),
  
  -- Client timestamp: when user actually answered (for clock skew detection)
  -- Optional, nullable if client doesn't provide it
  client_ts timestamp with time zone,
  
  -- Response time in milliseconds: how long user took to answer
  -- Used for analytics and detecting guessing vs. genuine recall
  -- Must be non-negative
  response_ms integer check (response_ms >= 0)
);

comment on table public.review_history is 'Immutable log of all flashcard review attempts';
comment on column public.review_history.difficulty is 'User-reported difficulty (drives SM-2 algorithm)';
comment on column public.review_history.answered_at is 'Server timestamp of review';
comment on column public.review_history.client_ts is 'Client timestamp (for detecting clock skew)';
comment on column public.review_history.response_ms is 'Time taken to answer in milliseconds';

-- =====================================================================
-- TABLE: flashcard_favourites
-- =====================================================================
-- Purpose: Many-to-many relationship for users to bookmark/favourite cards
-- Composite primary key ensures no duplicate favourites

create table public.flashcard_favourites (
  -- Composite primary key: user + flashcard
  user_id uuid not null references auth.users(id) on delete cascade,
  flashcard_id uuid not null references public.flashcards(id) on delete cascade,
  
  -- Timestamp when card was favourited
  added_at timestamp with time zone not null default now(),
  
  -- Composite primary key constraint
  primary key (user_id, flashcard_id)
);

comment on table public.flashcard_favourites is 'Many-to-many: users can favourite flashcards';
comment on column public.flashcard_favourites.added_at is 'When the card was added to favourites';

-- =====================================================================
-- TABLE: decks (Phase 2 placeholder)
-- =====================================================================
-- Purpose: Group flashcards into organized decks/collections
-- This is a placeholder table for Phase 2 functionality

create table public.decks (
  -- Primary key: UUID v7 for time-ordered IDs
  id uuid primary key default public.uuid_generate_v7(),
  
  -- Owner reference: which user owns this deck
  user_id uuid references auth.users(id) on delete cascade,
  
  -- Deck name
  name varchar(80) not null,
  
  -- Timestamp when deck was created
  created_at timestamp with time zone not null default now()
);

comment on table public.decks is 'Organized collections of flashcards (Phase 2 feature)';
comment on column public.decks.name is 'User-defined deck name';

-- =====================================================================
-- END OF MIGRATION
-- =====================================================================

